### ISSUE TITLE
Make grid more interactive

### ISSUE THREAD

**Issue by alexw1983** [alexw1983/jack-stuff#5]
# Story
**as a** player
**I need** to see which cell I am clicking on
**so that** I can use the game more effectively

# Description 
We want to make the game more interactive and easy to use. To do this we are going to have the background color of each div change when you hover over it and the cursor to go to a pointer so that we can click on it.

# Acceptance Criteria
1. When I hover my mouse over one of the squares in the grid the background color should change.
1. When I hover my mouse over one of the squares in the grid the cursor should change to a pointer.
1. This should be achieved entirely through CSS.

**Comment by Hoobachube** [comment]
completed interactive state
